script updates

diff --git a/.local/bin/scripts/chmenu b/.local/bin/scripts/chmenu
--- a/.local/bin/scripts/chmenu
+++ b/.local/bin/scripts/chmenu
@@ -1,116 +1,35 @@
 #!/bin/sh
 
 # print a numbered menu and allow the user to choose between its items
-# TODO: clean this up
 
 # handle signals
-for i in HUP INT QUIT ABRT KILL SEGV TERM STOP TSTP PWR; do
-    eval "trap '{
-        printf \"\n${0##*/}: recieved signal $i\n\"
-        exit 1
-    }' $i"
+for sig in HUP INT QUIT ABRT KILL SEGV TERM STOP TSTP PWR; do
+    trap '{ printf "\n%s: recieved signal %s\n" "${0##*/}" "'"$sig"'"; exit 1; }' "$sig"
 done
 
-# parse arguments
-while [ "$#" -gt 0 ]; do
-    case "$1" in
-        # treat options as absolute paths and strip directory parts
-        -b|--basenames) do_basenames="y"; shift ;;
+# if this argument was passed, print an option's number instead of the option itself
+test "$1" = "-n" && nummode="y" && shift
 
-        # obscure, i need it
-        -t|-tp|--theme|--theme-preview) do_themes="y"; shift ;;
+# we need a title and at least one option
+test -z "$2" && printf "%s: error: Missing arguments\n" "${0##*/}" >&2 && exit 1
 
-        # print a prefix before each option
-        -p|--prefix) print_prefix="$2"; shift 2 ;;
-        -p*)         print_prefix="${1##-p}"; shift ;;
-        --prefix=*)  print_prefix="${1##--prefix=}"; shift ;;
-
-        # print a suffix after each option
-        -s|--suffix) print_suffix="$2"; shift 2 ;;
-        -s*)         print_suffix="${1##-s}"; shift ;;
-        --suffix=*)  print_suffix="${1##--suffix=}"; shift ;;
-
-        # end option parsing
-        *) break ;;
-    esac
-done
-
-# title is required
-[ -n "$1" ] && {
-    title="$1"
-} || {
-    printf "${0##*/}: error: No menu title provided\n"
-    exit 1
-}
-
-# we don't need the title arg anymore, shift past it
+# print title and get option count
+printf "\n\033[1m%s\033[22m\n" "$1" >&2
 shift
+itmc="$#"
 
-# if no items are provided, exit
-[ -n "$1" ] || {
-    printf "${0##*/}: error: No menu items provided\n"
-    exit 1
-}
-
-# print a title
-printf "\033[1m%s\033[22m\n" "$title" >&2
-
-# initialize itm to 0
-itmc="0"
-
-# create list entries for each subsequent argument
-while [ "$#" -gt 0 ]; do
-    itmc=$((itmc+1))
-    eval "itm$itmc=\"$1\""
-
-    # strip path elements if applicable
-    [ "$do_basenames" = "y" ] && {
-          test "$(eval printf "\"\${itm$itmc##*/}\"" | wc -c)" -gt "${arglen:-0}" &&
-        arglen="$(eval printf "\"\${itm$itmc##*/}\"" | wc -c)"
-    } || {
-          test "$(eval printf "\"\$itm$itmc\"" | wc -c)" -gt "${arglen:-0}" &&
-        arglen="$(eval printf "\"\$itm$itmc\"" | wc -c)"
-    }
-
-    shift
+# list items
+for itm in "$@"; do
+    itmc="$((itmc-1))"
+    printf "\033[1m[\033[36m%s\033[39m]\033[22m %s\n" "$(($#-itmc))" "$itm" >&2
 done
 
-# we might not need it; if we do, do what needs to be done
-[ -n "$arglen" ] && [ -n "$print_suffix" ] && optlen="-$arglen"
-
-# print each choice provided in arguments
-for i in $(seq 1 $itmc); do
-    itmcol=""
-    eval "item=\"\$itm$i\""
-
-    # do tha thang
-    [ -r "$item/theme.conf" ] && {
-        itmcol="$(sed -n '2s/#//p' <"$item/theme.conf")"
-    }
-
-    # decide whether to color the item
-    case "$item" in
-        [yY]|[yY][eE][sS]|[tT]|[tT][rR][uU][eE])     itmcol="\033[1;32m" ;;
-            [nN]|[nN][oO]|[fF]|[fF][aA][lL][sS][eE]) itmcol="\033[1;31m" ;;
-    esac
-
-    # strip path elements if applicable
-    [ "$do_basenames" = "y" ] && item="${item##*/}"
-
-    # print the menu item and its ID
-    #eval "printf \"\033[1m[\033[36m%s\033[39m]\033[0m $itmcol%s\033[0m\" \"$itm\" \"$item\"" >&2
-    printf -- "\033[1m[\033[36m%s\033[39m]\033[0m $itmcol%${optlen}s\033[0m" "$i" "$print_prefix$item$print_suffix" >&2
-
-    # print a newline
-    printf "\n" >&2
-done
-
-# read the user's choice
+# get the user's choice
 while true; do
-    printf "\033[1mEnter your choice [\033[36m1\033[39m-\033[36m$i\033[39m]\033[22m " >&2
+    printf "\033[1mEnter your choice [\033[36m1\033[39m-\033[36m$#\033[39m]\033[22m " >&2
     read inum
-    test "$inum" -gt 0 -a "$inum" -le "$itmc" >/dev/null 2>&1 && break
+    test "$inum" -gt "0" -a "$inum" -le "$#" >/dev/null 2>&1 && break
 done
 
-# print the item the user chose
-eval "printf \"\$itm$inum\""
+# print the option or its number
+eval "printf \"$(test "$nummode" = "y" || printf '$')$inum\""
diff --git a/.local/bin/scripts/generate-theme b/.local/bin/scripts/generate-theme
--- a/.local/bin/scripts/generate-theme
+++ b/.local/bin/scripts/generate-theme
@@ -3,38 +3,50 @@
 # generate theme configurations
 # TODO: overhaul macros and use a preprocessor instead of sed
 
-# check for commands
-require_cmd() {
-    for i in "$@"; do
-        command -v "$i" >/dev/null 2>&1 || ! printf "$i: command not found\n" >&2 || return 127
+# theme select menu
+chtheme() {
+    test -z "$1" && return 1
+    printf "\n\033[1mApplying which theme?\033[22m\n" >&2
+    itmc="$#"
+    for itm in "$@"; do
+        itmc="$((itmc-1))"
+        printf "\033[1m[\033[36m%s\033[39m]\033[22m " "$(($#-itmc))" >&2
+        printf "$(sed -n '2s/^#\\e\(\[38;2;[0-9]\+;[0-9]\+;[0-9]\+m\)\\e\(\[48;2;[0-9]\+;[0-9]\+;[0-9]\+m\)$/\x1B\1\x1B\2/p' <"$itm/theme.conf" 2>/dev/null)" >&2
+        printf "%s\033[0m\n" "${itm##*/}" >&2
     done
+    while true; do
+        printf "\033[1mEnter your choice [\033[36m1\033[39m-\033[36m$#\033[39m]\033[22m " >&2
+        read inum
+        test "$inum" -gt "0" -a "$inum" -le "$#" >&- 2>&- && break
+    done
+    eval "printf \"\${$inum##*/}\""
 }
 
-# we need these
-require_cmd find sed chmenu || exit 127
+# we need sed
+for c in find sed; do
+    test -z "$(command -v "$c")" && printf "$c: command not found\n" >&2 && exit 127
+done
+
+# look for themes in here
+themedir="${XDG_CONFIG_HOME:-$HOME/.config}/themes"
 
 # get name of theme from $1
-[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/themes/${1:+$1/}theme.conf" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/themes/${1:+$1/}theme.conf"
+test -r "$themedir${1:+/$1/}theme.conf" && theme="$1"
 
-# get name of theme from interactive input
-[ ! -r "${XDG_CONFIG_HOME:-$HOME/.config}/themes/${1:+$1/}theme.conf" ] && {
-    # get a list of themes
-    tchoices="$(for i in $(find "${XDG_CONFIG_HOME:-$HOME/.config}/themes/" -type d -not -path "${XDG_CONFIG_HOME:-$HOME/.config}/themes/"); do test -d "$i" || continue; printf "$i\t"; done)"
+# or pick one
+IFS="$(printf "\n\t")"
+test -z "$theme" && theme="$(chtheme $(find "$themedir" -mindepth 1 -type d 2>/dev/null))"
+test -z "$theme" && theme="$(chtheme $(for d in "$themedir"/* "$themedir"/*/*; do test -d "$d" && printf "%s\n" "$d"; done))"
+IFS="$(printf " \n\t")"
 
-    # choose the theme
-    OLDIFS="$IFS"; IFS="$(printf '\t')"; tchoice="$(chmenu -t -b 'Applying which theme?' $tchoices)"; IFS="$OLDIFS"
-
-    # apply it if possible
-    test ! -r "$tchoice/theme.conf" && printf "${0##*/}: error: $tchoice/theme.conf: No such file or directory" && exit 1
-    . "$tchoice/theme.conf"
-}
+# source theme file
+. "$themedir/$theme/theme.conf" || exit "$?"
 
 # generate theme-specific config files from templates
-for i in $(find "${XDG_CONFIG_HOME:-$HOME/.config}" "${XDG_DATA_HOME:-$HOME/.local/share}" -type f -name '___*') $(find "${XDG_CONFIG_HOME:-$HOME/.config}" "${XDG_DATA_HOME:-$HOME/.local/share}" -type f -name '.___*'); do
-    dir="${i%/*}"
-    name="${i##*/}"
-    name="${name##___}"
-    test "${name#.}" != "$name" && name=".${name##.___}"
+for f in $(find "${XDG_CONFIG_HOME:-$HOME/.config}" "${XDG_DATA_HOME:-$HOME/.local/share}" -type f | sed -n '/\/\.\?___/p'); do
+    dir="${f%/*}"
+    name="${f##*/}"
+    test "${name#.}" != "$name" && name=".${name##.___}" || name="${name##___}"
 
     # substitution for fonts, colors, vim colorschemes, and directories
     sed \
@@ -89,21 +101,8 @@ for i in $(find "${XDG_CONFIG_HOME:-$HOME/.config}" "${XDG_DATA_HOME:-$HOME/.loc
         -e "s%#::musicdir::#%${XDG_MUSIC_DIR:-$HOME/Music}%g" \
         -e "s%#::picdir::#%${XDG_PICTURES_DIR:-$HOME/Pictures}%g" \
         -e "s%#::videodir::#%${XDG_VIDEOS_DIR:-$HOME/Videos}%g" \
-    <"$i" >"$dir/$name"
+    <"$f" >"$dir/$name"
 done
 
-# reload the font cache
-command -v fc-cache >/dev/null 2>&1 && fc-cache
-
-# reload waybar
-command -v waybar >/dev/null 2>&1 && pidof waybar >/dev/null 2>&1 && test -n "$WAYLAND_DISPLAY" && pkill waybar && setsid -f waybar >/dev/null 2>&1
-
-# reload yambar
-command -v yambarr >/dev/null 2>&1 && {
-    command -v yambar >/dev/null 2>&1 && pidof yambar >/dev/null 2>&1 && test -n "$WAYLAND_DISPLAY" && pkill yambar && setsid -f yambarr >/dev/null 2>&1
-} || {
-    command -v yambar >/dev/null 2>&1 && pidof yambar >/dev/null 2>&1 && test -n "$WAYLAND_DISPLAY" && pkill yambar && setsid -f yambar >/dev/null 2>&1
-}
-
-# reload riverwm theme
-command -v riverctl >/dev/null 2>&1 && pidof river >/dev/null 2>&1 && test -n "$WAYLAND_DISPLAY" && sh "${XDG_CONFIG_HOME:-$HOME/.config}/river/theme" >/dev/null
+# reload theme if we can
+test -n "$(command -v reload-theme)" && reload-theme
