so many changes, more to be made

diff --git a/.local/bin/scripts/clear-theme b/.local/bin/scripts/clear-theme
--- a/.local/bin/scripts/clear-theme
+++ b/.local/bin/scripts/clear-theme
@@ -2,16 +2,12 @@
 
 # clear generated theme configurations
 
-# load shell functions
-[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/shell/functions" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/functions"
-
-# we need these
-require-cmd find rm || exit 127
+# check for commands
+for i in find rm; do
+    command -v "$i" >/dev/null 2>&1 || ! printf "$i: command not found\n" >&2 || exit 127
+done
 
 # rm theme-specific config files
-for i in $(find "${XDG_CONFIG_HOME:-$HOME/.config}" "${XDG_DATA_HOME:-$HOME/.local/share}" -type f -name '___*') \
-         $(find "${XDG_CONFIG_HOME:-$HOME/.config}" "${XDG_DATA_HOME:-$HOME/.local/share}" -type f -name '.___*'); do
-    dir="${i%/*}"
-    name="${i##*___}"
-    rm -v "$dir/$name"
+for i in $(find "${XDG_CONFIG_HOME:-$HOME/.config}" "${XDG_DATA_HOME:-$HOME/.local/share}" -type f -name '___*' -o -name '.___*'); do
+    test "${i##*/.___}" != "$i" && rm -v "${i%/*}/.${i##*___}"  || rm -v "${i%/*}/${i##*___}"
 done
diff --git a/.local/bin/scripts/take-screenshot b/.local/bin/scripts/take-screenshot
--- a/.local/bin/scripts/take-screenshot
+++ b/.local/bin/scripts/take-screenshot
@@ -2,17 +2,23 @@
 
 # screenshot utility frontend
 
-# load shell functions
-[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/shell/functions" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/functions"
+# check for commands
+require_cmd() {
+    for i in "$@"; do
+        command -v "$i" >/dev/null 2>&1 || ! printf "$i: command not found\n" >&2 || exit 127
+    done
+}
 
 # use $1 as img name
-[ "$#" -gt 0 ] && img="${1%.png}" && img="${img%.jpg}" && img="${img%.jpeg}" && img="${img%.webp}" && img="${img%.bmp}"
+test "$#" -gt 0 && img="$1" && for i in png jpg jpeg jfif avif webp bmp; do
+    img="${img%".$i"}"
+done
 
 # otherwise set img name
-[ -z "$img" ] && {
+test -z "$img" && {
     img="${XDG_PICTURES_DIR:-$HOME/Pictures}/screenshot"
     command -v date >/dev/null 2>&1 && img="${XDG_PICTURES_DIR:-$HOME/Pictures}/$(date +'%Y-%m-%d-%H%M%S_')screenshot"
-    test ! -d "${XDG_PICTURES_DIR:-$HOME/Pictures}" && ! mkdir -p "${XDG_PICTURES_DIR:-$HOME/Pictures}" && exit $1
+    test -d "${XDG_PICTURES_DIR:-$HOME/Pictures}" || mkdir -p "${XDG_PICTURES_DIR:-$HOME/Pictures}" || exit $1
 }
 
 # numbered suffix for duplicate files
@@ -29,32 +35,32 @@
 # take a screenshot on wayland
 [ -n "$WAYLAND_DISPLAY" ] && {
     # `grim` is required for taking wayland screenshots
-    require-cmd grim || exit 127
+    require_cmd grim
 
     # get a selection using slurp if installed
     command -v slurp >/dev/null 2>&1 && {
         xypos="$(slurp 2>/dev/null)"
         eval "grim${xypos:+ -g \"$xypos\"} \"$img\"" >/dev/null 2>&1
-        exit $?
+        exit "$?"
     } || {
         grim "$img" >/dev/null 2>&1
-        exit $?
+        exit "$?"
     }
 }
 
 # take a screenshot on x11
 [ -n "$DISPLAY" ] && {
     # `scrot` is required for taking x11 screeenshots
-    require-cmd scrot || exit 127
+    require_cmd scrot
 
     # take the screenshot
     scrot "$img" -s >/dev/null 2>&1
-    exit $?
+    exit "$?"
 }
 
 # fbgrab is required to take framebuffer screenshots
-require-cmd fbgrab || exit 127
+require_cmd fbgrab
 
 # take a screenshot of a framebuffer console
 fbgrab "$img" >/dev/null 2>&1
-exit $?
+exit "$?"
