lots of script updates

diff --git a/.local/bin/scripts/elinks b/.local/bin/scripts/elinks
--- a/.local/bin/scripts/elinks
+++ b/.local/bin/scripts/elinks
@@ -1,34 +1,15 @@
 #!/bin/sh
 
-# wrapper over elinks that deletes .rndjk
+# wrapper around `elinks` for post-usage cleanup
 
-# add to path
-pathadd() {
-    case ":$PATH:" in
-        *:"${1%/}":*) ;;
-        *) [ -d "$1" ] && { [ "$2" = "-a" ] && export PATH="${PATH:+$PATH:}${1%/}" || export PATH="${1%/}${PATH:+:$PATH}"; } ;;
-    esac
-}
+# load shell functions
+[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/shell/functions" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/functions"
 
-# stuff
-OLDPATH="$PATH"
-OLDIFS="$IFS"
-PATH=""
-IFS=":"
+# we need these
+require-cmd syspath rm || exit 127
 
-# discard path elements in the home directory (ex. this script)
-for i in $OLDPATH; do
-    case "$i" in *"$HOME"*) continue ;; esac; pathadd "$i"
-done
+# find the system's elinks and run it
+syspath elinks "$@"
 
-# get old ifs
-IFS="$OLDIFS"
-
-# run elinks
-if command -v elinks >/dev/null 2>&1; then
-    elinks "$@"
-    rm -rf "$HOME/.rnd"
-else
-    printf "${SHELL##*/}: elinks: command not found\n" >&2
-    exit 127
-fi
+# clean up the junk 'random seed' file
+rm -rf "$HOME/.rnd"
diff --git a/.local/bin/scripts/generate-theme b/.local/bin/scripts/generate-theme
--- a/.local/bin/scripts/generate-theme
+++ b/.local/bin/scripts/generate-theme
@@ -1,86 +1,42 @@
 #!/bin/sh
 
-# needs these commands
-require-cmd find sed || exit 1
+# generate theme configurations
+# TODO: overhaul macros and use a preprocessor instead of sed
 
-# parse args
-while [ "$#" -gt 0 ]; do
-    case "$1" in
-        -v|--verbose) verbose="y"; shift ;;
-        [lL]|-[lL]|--list|list|[cC]|-[cC]|--choose|choose) choose="y"; shift ;;
-        *) break ;;
-    esac
-done
+# load shell functions
+[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/shell/functions" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/functions"
 
-# load the theme config file
-[ -r "${XDG_DATA_HOME:-$HOME/.local/share}/dots/themes/${1:+$1/}theme.conf" ] && [ "$choose" != "y" ] && {
-    . "${XDG_DATA_HOME:-$HOME/.local/share}/dots/themes/${1:+$1/}theme.conf"
-} || {
-    # search the directory for theme dirs
-    for i in $(find "${XDG_DATA_HOME:-$HOME/.local/share}/dots/themes/" -type d -not -path "${XDG_DATA_HOME:-$HOME/.local/share}/dots/themes/"); do
-        # store the dir
-        [ -d "$i" ] && tchoices="${tchoices:+$tchoices }'$i'"
-    done
+# we need these
+require-cmd find sed chmenu || exit 127
+
+# get name of theme from $1
+[ -r "${XDG_DATA_HOME:-$HOME/.local/share}/dots/themes/${1:+$1/}theme.conf" ] && . "${XDG_DATA_HOME:-$HOME/.local/share}/dots/themes/${1:+$1/}theme.conf"
+
+# get name of theme from interactive input
+[ ! -r "${XDG_DATA_HOME:-$HOME/.local/share}/dots/themes/${1:+$1/}theme.conf" ] && {
+    # get a list of themes
+    tchoices="$(for i in $(find "${XDG_DATA_HOME:-$HOME/.local/share}/dots/themes/" -type d -not -path "${XDG_DATA_HOME:-$HOME/.local/share}/dots/themes/"); do test -d "$i" || continue; printf "$i\t"; done)"
 
     # choose the theme
-    tchoice="$(eval "nmenu -t -b 'Applying which theme?' $tchoices")"
+    OLDIFS="$IFS"; IFS="$(printf '\t')"; tchoice="$(chmenu -t -b 'Applying which theme?' $tchoices)"; IFS="$OLDIFS"
 
     # apply it if possible
-    [ -r "$tchoice/theme.conf" ] && {
-        . "$tchoice/theme.conf"
-    } || {
-        printf "${0##*/}: error: $tchoice/theme.conf: No such file or directory"
-        exit 1
-    }
+    test ! -r "$tchoice/theme.conf" && printf "${0##*/}: error: $tchoice/theme.conf: No such file or directory" && exit 1
+    . "$tchoice/theme.conf"
 }
 
 # generate theme-specific config files from templates
 for i in $(find "${XDG_CONFIG_HOME:-$HOME/.config}" "${XDG_DATA_HOME:-$HOME/.local/share}" -type f -name '___*') $(find "${XDG_CONFIG_HOME:-$HOME/.config}" "${XDG_DATA_HOME:-$HOME/.local/share}" -type f -name '.___*'); do
     dir="${i%/*}"
     name="${i##*/}"
-
-    # if dot prefix, fix this
-    [ "${name#.}" != "$name" ] && {
-        name=".${name##.___}"
-    } || {
-        name="${name##___}"
-    }
+    name="${name##___}"
+    test "${name#.}" != "$name" && name=".${name##.___}"
 
     # substitution for fonts, colors, vim colorschemes, and directories
-    [ "$verbose" = "y" ] && printf "sed <$i >$dir/$name\n"
     sed \
         -e "s/#::font-monospace::#/${theme_font_monospace:-monospace}/g" \
         -e "s/#::font-serif::#/${theme_font_serif:-serif}/g" \
         -e "s/#::font-sans-serif::#/${theme_font_sans_serif:-sans-serif}/g" \
-        -e "s/#::font-serif::#/${theme_font_serif:-EB Garamond}/g" \
-        -e "s/#::font-sans-serif::#/${theme_font_sans_serif:-Aileron}/g" \
-        -e "s/#::font-monospace::#/${theme_font_monospace:-Fira Code}/g" \
-        -e "s/#::font-sans-serif-arabic::#/${theme_font_sans_serif_arabic:-${theme_font_serif_arabic:-sans-serif}}/g" \
-        -e "s/#::font-serif-arabic::#/${theme_font_serif_arabic:-${theme_font_sans_serif_arabic:-serif}}/g" \
-        -e "s/#::font-sans-serif-bengali::#/${theme_font_sans_serif_bengali:-${theme_font_serif_bengali:-sans-serif}}/g" \
-        -e "s/#::font-serif-bengali::#/${theme_font_serif_bengali:-${theme_font_sans_serif_bengali:-serif}}/g" \
-        -e "s/#::font-sans-serif-chinese-simplified::#/${theme_font_sans_serif_chinese_simplified:-${theme_font_serif_chinese_simplified:-sans-serif}}/g" \
-        -e "s/#::font-serif-chinese-simplified::#/${theme_font_serif_chinese_simplified:-${theme_font_sans_serif_chinese_simplified:-serif}}/g" \
-        -e "s/#::font-sans-serif-chinese-traditional::#/${theme_font_sans_serif_chinese_traditional:-${theme_font_serif_chinese_traditional:-sans-serif}}/g" \
-        -e "s/#::font-serif-chinese-traditional::#/${theme_font_serif_chinese_traditional:-${theme_font_sans_serif_chinese_traditional:-serif}}/g" \
-        -e "s/#::font-sans-serif-cypriot::#/${theme_font_sans_serif_cypriot:-${theme_font_serif_cypriot:-sans-serif}}/g" \
-        -e "s/#::font-serif-cypriot::#/${theme_font_serif_cypriot:-${theme_font_sans_serif_cypriot:-serif}}/g" \
-        -e "s/#::font-sans-serif-devanagari::#/${theme_font_sans_serif_devanagari:-${theme_font_serif_devanagari:-sans-serif}}/g" \
-        -e "s/#::font-serif-devanagari::#/${theme_font_serif_devanagari:-${theme_font_sans_serif_devanagari:-serif}}/g" \
-        -e "s/#::font-sans-serif-gurmukhi::#/${theme_font_sans_serif_gurmukhi:-${theme_font_serif_gurmukhi:-sans-serif}}/g" \
-        -e "s/#::font-serif-gurmukhi::#/${theme_font_serif_gurmukhi:-${theme_font_sans_serif_gurmukhi:-serif}}/g" \
-        -e "s/#::font-sans-serif-hebrew::#/${theme_font_sans_serif_hebrew:-${theme_font_serif_hebrew:-sans-serif}}/g" \
-        -e "s/#::font-serif-hebrew::#/${theme_font_serif_hebrew:-${theme_font_sans_serif_hebrew:-serif}}/g" \
-        -e "s/#::font-sans-serif-japanese::#/${theme_font_sans_serif_japanese:-${theme_font_serif_japanese:-sans-serif}}/g" \
-        -e "s/#::font-serif-japanese::#/${theme_font_serif_japanese:-${theme_font_sans_serif_japanese:-serif}}/g" \
-        -e "s/#::font-sans-serif-korean::#/${theme_font_sans_serif_korean:-${theme_font_serif_korean:-sans-serif}}/g" \
-        -e "s/#::font-serif-korean::#/${theme_font_serif_korean:-${theme_font_sans_serif_korean:-serif}}/g" \
-        -e "s/#::font-sans-serif-mongolian::#/${theme_font_sans_serif_mongolian:-${theme_font_serif_mongolian:-sans-serif}}/g" \
-        -e "s/#::font-serif-mongolian::#/${theme_font_serif_mongolian:-${theme_font_sans_serif_mongolian:-serif}}/g" \
-        -e "s/#::font-sans-serif-syriac::#/${theme_font_sans_serif_syriac:-${theme_font_serif_syriac:-sans-serif}}/g" \
-        -e "s/#::font-serif-syriac::#/${theme_font_serif_syriac:-${theme_font_sans_serif_syriac:-serif}}/g" \
-        -e "s/#::font-sans-serif-thai::#/${theme_font_sans_serif_thai:-${theme_font_serif_thai:-sans-serif}}/g" \
-        -e "s/#::font-serif-thai::#/${theme_font_serif_thai:-${theme_font_sans_serif_thai:-serif}}/g" \
         -e "s/#::vim-colorscheme::#/${theme_vim_colorscheme:-default}/g" \
         -e "s/#::vim-transparency::#/${theme_vim_transparency:-false}/g" \
         -e "s/#::rootbg::#/$theme_rootbg/g" \
@@ -136,12 +92,7 @@ done
 command -v fc-cache >/dev/null 2>&1 && fc-cache
 
 # reload waybar
-command -v waybar >/dev/null 2>&1 && {
-    [ -n "$(pidof waybar 2>/dev/null)" ] && pkill waybar
-    command -v setsid >/dev/null 2>&1 && [ -n "$WAYLAND_DISPLAY" ] && setsid -f waybar >/dev/null 2>&1
-}
+command -v waybar >/dev/null 2>&1 && pidof waybar >/dev/null 2>&1 && command -v setsid >/dev/null 2>&1 && test -n "$WAYLAND_DISPLAY" && pkill waybar && setsid -f waybar >/dev/null 2>&1
 
 # reload river theme if riverwm is active
-command -v riverctl >/dev/null 2>&1 && {
-    [ -n "$(pidof river 2>/dev/null)" ] && [ -n "$WAYLAND_DISPLAY" ] && sh "${XDG_CONFIG_HOME:-$HOME/.config}/river/theme" >/dev/null
-}
+command -v riverctl >/dev/null 2>&1 && pidof river >/dev/null 2>&1 && test -n "$WAYLAND_DISPLAY" && sh "${XDG_CONFIG_HOME:-$HOME/.config}/river/theme" >/dev/null
