update some scripts

diff --git a/.local/bin/scripts/require-cmd b/.local/bin/scripts/require-cmd
--- a/.local/bin/scripts/require-cmd
+++ b/.local/bin/scripts/require-cmd
@@ -1,8 +1,6 @@
 #!/bin/sh
 
 # script to require a command
-while [ "$#" -gt 0 ]; do
-    command -v "$1" >/dev/null 2>&1 && shift && continue
-    printf "$1: command not found\n" >&2
-    exit 127
+for i in "$@"; do
+    ! command -v "$i" >/dev/null 2>&1 && printf "$i: command not found\n" >&2 && exit 127
 done
